# -*- coding: utf-8 -*-
"""COMP6200-20240123-Workshop Week 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nqVEBFAS8-5yHdzyy1Jsjsk59k6_u0e7

# COMP2200/COMP6200 Week 1 Practical

The goal of this week's practical is to get you started using Python, Jupyter Notebooks, and Git, three tools that you will use through the semester in your work.  

**Python** is our language of choice in COMP2200/COMP6200. If you do not have any experience of using Python, you need to learn basic Python coding.

You are looking at a **Jupyter Notebook**, it is a document that mixes text, code and the output of the code. A lot of your work will be creating notebooks like this to present your analysis.  

**Git** is a distributed version control system (DVCS), you will use it to keep track of your work and ensure that you have a backup copy of what you are doing. You should have checked this notebook out of **Github** using Git. Your task this week is to complete some programming work in this worksheet and commit your changes to your own Bitbucket repository.

## Python Basics

Your task this week is to complete some basic programming tasks with Python in this worksheet.  There are questions below with a space for you to write code to achieve the given outcomes. Write the code, test it, and when you are done, submit your work as described at the end of the notebook.

The tasks aren't meant to be complicated Python problems, just some simple tasks to get you started with this process.  

## String Manipulation

The next cell defines three strings that you will use in the first group of questions. Note that the first uses single quotes, the second uses double quotes and the third uses three double quotes since it includes newline characters.  These are all valid ways of writing strings in Python and are equivalent.
"""

title = 'Data Science'
code = "COMP2200/COMP6200"
description = """This unit introduces students to the fundamental techniques and
tools of data science, such as the graphical display of data,
predictive models, evaluation methodologies, regression,
classification and clustering. The unit provides practical
experience applying these methods using industry-standard
software tools to real-world data sets. Students who have
completed this unit will be able to identify which data
science methods are most appropriate for a real-world data
set, apply these methods to the data set, and interpret the
results of the analysis they have performed. """


# x_var - 1

"""Write code to print the length of these strings.

Write code to create a new string in a variable 'summary' that contains the code, title and the first 20 characters of the description, with a ':' character between each one (ie 'COMP2200/COMP6200:Data Science:This unit...'
"""

test  = '0123456789'
test1 = '3456789'

print(test[0:5])
print(test1[0:5])

print(test[2:5])
print(test1[2:5])

print(test[0])
print(test1[0])

#write your code here: print the lenght of these strings
#len(title)
#len(code)
#len(description)

print(len(title))
print(len(code))
print(len(description))

print(12)

# write your code here: create a new string summary and then print it
summary = title + ':' + code + ':' + description[0:20]
sum = 1 + 2
print(summary)
print(1,2,1+2)
print(1,2,sum)

"""Write code to find the number of words in the description.  Hint, this is easy in Python since strings support the [split method](https://docs.python.org/3.6/library/stdtypes.html#str.split) that returns a list of strings after splitting on whitespace (or another character if you wish).   Try split on the string, then find out how many strings are in the resulting list."""

#write your code here
print(description.split())

print(description)
print(len(description.split()))

print(description.split(' '))
print(len(description.split(' ')))

print(description.split(','))
print(len(description.split(',')))

print(description.split('.'))
print(len(description.split('.')))

print(description.split('and'))
print(len(description.split('and')))

print(description.split('\n'))
print(len(description.split('\n')))

"""# Control Structures

Here you will explore Python control structures - conditionals and loops.  

Write a for loop over the words in the description and count how many times the word 'unit' occurs.  Your solution will have an if statement inside the for loop.

Here you will encounter Python's required indentation for the first time. This will annoy you at first but you will learn to either love it or hate it with time...
"""

# write your code here
print(description)

# method 1
t = 0
for i in description.split():
  if i == "unit":
    t = t + 1
  else:
    t = t
print(t)

# method 2
description.count("unit")

"""You can iterate over any sequence with a for loop, including the characters in a string.  Write a for loop over the characters in the description that prints out 'Comma!' every time it sees a comma."""

#write your code here
print(description)
print("There are", description.count(","), "',' in below paragraph. They include:)

t = 0
for i in description.split(","):
  print(i)

"""## Functions

Python is a dynamically typed language so we don't need to declare the type of a variable or declare the return type of a function (although Python 3 introduced optional [type hints](https://docs.python.org/3/library/typing.html)).  Apart from that the idea of writing a function in Python is the same as in Processing or (methods in) Java.

Write a function that takes a single string argument and returns the number of words in the string using the code you wrote above to count words.
"""

#write your code here
print(description)
print("There are ", len(description.split()), " words")

cut = description[9:48]
print("I choose the string '", cut, "' which has ",len(cut.split()), " words")

#write your code here

"""Use your function to find the number of words in the description string defined above."""

#write your code here

"""## Data and Plotting

Just to give you a taste of some of the capabilities of Jupyter notebooks and Python we will look at a very simple example of data handling and plotting.  First I'll import some libraries that will allow us to do this: `pandas` handles data and `matplotlib` does the plotting.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

"""Now I will define a data frame with some data about the number of students in this unit and the pass and fail rate.  This is like an array but can do a lot more. The last line in the cell evaluates the data frame so that it gets displayed. Notice that last year, none has failed - let's keep it that way!"""

classdata = pd.DataFrame({
    'year': [2018, 2019, 2020, 2021],
    'students': [38, 64, 247, 377],
    'pass': [32, 50, 247, 377],
    'fail': [6, 14, 0, 0]
})
classdata

"""Now we will create a simple plot."""

classdata.plot(kind='bar', x='year', y='students')

"""Experiment a little with this to try other options. Look at [the documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html) for an idea. For example, can you make a line plot rather than a bar plot? Can you plot the other columns."""

# your code here for a different plot

"""Next we will add a new column, calculated from the pass and students columns to hold the percentage pass rate.  This shows how we can do calculations over the entire array of data using `pandas`.  """

classdata['passrate'] = 100*classdata['pass']/classdata['students']
classdata

"""Now create a new plot showing the change in percentage pass rate over the three years."""

# your code here

"""## Checkpoint

You got your copy of this notebook by forking and then cloning my Github repository.  Now that you have made some changes you should commit your work with a suitable commit message and push your changes back to your Github repository.  Show your tutor your updated Github repository to get your checkpoint mark.
"""

